### ISSUE TITLE
The statements counters are not update when using coverage.xml

### ISSUE THREAD

**Issue by ricardolsmendes** [MishaKav/pytest-coverage-comment#108]
Hi there!

I've set up this action in one of my repos and `pytest-xml-coverage-path` is my preferred option to handle the output of pytest-coverage. However, I noticed the `stmts` counters are always 0 at the file level in the coverage report, as shown in the below screenshot:

<img width="1180" alt="Screenshot 2023-01-23 at 13 34 22" src="https://user-images.githubusercontent.com/30279287/214097735-4e043b54-9f3b-41e6-b889-bdeb3cb7767e.png">

I guess I found the root cause and will submit a fix soon.

**Comment by MishaKav** [comment]
I merged your changes and release a new version, which you can use:

```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
```
or use a specific version
```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.43
```

Thanks again, for the contribution!
