### ISSUE TITLE
Add pull_request_target as valid event

### ISSUE THREAD

**Issue by chrisoro** [MishaKav/pytest-coverage-comment#112]
Would it be possible to support this event? I would like to use this in my (protected) environment where there are no drawbacks to pull_request_target and it secret handling.

**Comment by MishaKav** [comment]
Sure it possible. I will add support for it very soon.

**Comment by chrisoro** [comment]
Awesome, thank you!

**Comment by MishaKav** [comment]
I add support for this, you can use:

```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
```
or use a specific version
```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.44
```
