### ISSUE TITLE
badge broken

### ISSUE THREAD

**Issue by sayurionishi** [MishaKav/pytest-coverage-comment#141]
Hi, the image of the badge is always broken recently. It was working before, not sure if it was related to my code or the plugin.
Hope you can help me check this issue, thank you :) 
![image](https://github.com/MishaKav/pytest-coverage-comment/assets/64181380/749d1a32-1ce9-48ec-b1b4-4759e3a5efe6)
<img width="450" alt="image" src="https://github.com/MishaKav/pytest-coverage-comment/assets/64181380/240c3d28-530c-410d-a30d-410b8d733a48">

**Comment by MishaKav** [comment]
Can you please click on edit this comment and send me the "pure markdown" code?

**Comment by sayurionishi** [comment]
Hi @MishaKav , is this enough?
`<a href="https://github.com/cellanome/flowcell_server/blob/01fd0ffcfe97d5ec642115da7f487cc2a5349015/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-50%
25-orange.svg" /></a>`

**Comment by MishaKav** [comment]
It is hard to test it without actual data, but I think this release should fix your issue.

Can you please try new version `v1.1.48` or just run on `main` and update if it worked for you?

```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
```
or use a specific version
```YAML
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.48
```

**Comment by sayurionishi** [comment]
Hi @MishaKav , it works now! Thank you very much! :)

**Comment by sayurionishi** [comment]
Hi @MishaKav the badge in the email was not fixed, my apologies
![image](https://github.com/MishaKav/pytest-coverage-comment/assets/64181380/54e09002-9cae-4922-b3eb-b63e813caea9)

**Comment by MishaKav** [comment]
Are you using the latest version? If so can you please click on edit this comment in GitHub and send me the "pure markdown" code?

**Comment by sayurionishi** [comment]
Yes, the badge in the PR itself was already fixed. The badge in the email remained broken.
`
<a href="https://github.com/cellanome/flowcell_server/blob/70fb8c28c109f169ccc941b8a8c29483e89e4059/README.md"><img alt="Coverage" src="https://img.shields.io/badge/Coverage-50%25-orange.svg" /></a>`
<img width="780" alt="image" src="https://github.com/MishaKav/pytest-coverage-comment/assets/64181380/bbcd76e9-69e9-472e-a231-9f85809f5663">
![image](https://github.com/MishaKav/pytest-coverage-comment/assets/64181380/f9006a2a-71ae-4a32-8f58-cb90a24db87e)

**Comment by MishaKav** [comment]
It's not the problem in the `github-action`, it's the problem of the `email-client` that you use.
The `coverage` icon comes as `svg` and shown as `image`, browsers understand this and show the image.
For example `gmail` doesn't support `svg` format images in the email itself.

**Comment by sayurionishi** [comment]
I see, thank you for checking @MishaKav :)
