### ISSUE TITLE
Body too long

### ISSUE THREAD

**Issue by Bufias** [MishaKav/pytest-coverage-comment#15]
Hi! Congratulatons for the action, looks very nice.
I am having the following error: **Body is too long (maximum is 65536 characters)**
I am trying to get the coverage of a Django application, so I am running this command:
`pytest --disable-warnings --junitxml=pytest.xml --cov | tee pytest-coverage.txt`

Am I doing something wrong? Or it is a limit on the action?
Thanks!

**Comment by MishaKav** [comment]
It's a limitation of GitHub comment size. It seems like you have a very long report with missing lines.
You can try to enable the `hide-report: true`, then you will be able to see the coverage badge and junit sumarry.

**Comment by MishaKav** [comment]
Solve this error, now you will see a relevant warning with suggestions on what to do when the comment is too long.
Please use the latest version

```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.5

```
