### ISSUE TITLE
Links in Coverage Report are broken

### ISSUE THREAD

**Issue by SchernHe** [MishaKav/pytest-coverage-comment#152]
Hey, 

first of all thanks for this great action. Really nice to close the gap to the feature in GitLab. 

However, it seems the links in the coverage report are not set properly e.g. [check-out this link from the README](https://github.com/MishaKav/pytest-coverage-comment/blob/680f562642190a6a28f6c54785c767e2586b44b8/functions/example_completed/example_completed.py)

Is there a possibility to adjust the links in order to actually move to the correct location? So pointing towards the feature branch or main? 

Thanks!

**Comment by MishaKav** [comment]
I'm not sure I got you, but you have a `coverage-path-prefix` param that can adjust paths to the links.
You have some issues when it is discussed:

https://github.com/MishaKav/pytest-coverage-comment/issues/125 | https://github.com/MishaKav/pytest-coverage-comment/issues/92 | https://github.com/MishaKav/pytest-coverage-comment/issues/80
