### ISSUE TITLE
"Cannot destructure property coverage of report as it is null" error while running coverage with github workflow

### ISSUE THREAD

**Issue by nakuls003** [MishaKav/pytest-coverage-comment#156]
Run MishaKav/pytest-coverage-comment@main
Warning: File "/home/runner/work/sms-gateway/sms-gateway/coverage.xml" doesn't exist
Error: TypeError: Cannot destructure property 'coverage' of 'report' as it is null.
Error: Cannot destructure property 'coverage' of 'report' as it is null.

**Comment by MishaKav** [comment]
Can you please provide more information on this?
- In which command you generate the report?
- With which configs do you run this action?
- If you can I will be glad to see the `pytest-coverage.txt` file

**Comment by nakuls003** [comment]
@MishaKav -- Nevermind, turns out the tests never ran due to an error and hence coverage file wasn't created. Closing the issue. Thanks for the quick response.
