### ISSUE TITLE
Escape character seems to be failing the basic example

### ISSUE THREAD

**Issue by HagegeR** [MishaKav/pytest-coverage-comment#167]
Hi, @MishaKav, thanks for your fantastic action!

I am trying to enable the badge update workflow and it did not work for me, so I tested each steps separately and got to here:
https://github.com/MishaKav/pytest-coverage-comment/blob/0e5d9396932b388ef7f313db17977815050b0cd5/README.md?plain=1#L153
```
Coverage Percentage - 82%
Coverage Color - green
Coverage Html - ""
/home/runner/_work/_temp/58ddf838-2bbf-44c9-b520-6d9de2814490.sh: line 4: syntax error near unexpected token `<'
```

My understanding is that the HTML result contains escape characters that the script doesn't know how to ignore.
It seems like the jest version you made have some improvements in that part of the code, is it possible to try and align their code base somehow maybe?

I also saw here another issue: https://github.com/MishaKav/pytest-coverage-comment/blob/0e5d9396932b388ef7f313db17977815050b0cd5/.github/workflows/update-coverage-on-readme.yml#L32
summary_report is not a valid id

Hoping to hear back from you soon :)

**Comment by MishaKav** [comment]
Hey,
1. Try to run your example without printing `echo "Coverage Html..."` (just remove this line)
2. You are right, instead of `summary_report`, it should be `coverageComment` (I've already update the `main` branch with that)

**Comment by HagegeR** [comment]
thanks for the swift response!
I actually need the Coverage Html because I wanted to use the example here:
https://github.com/MishaKav/pytest-coverage-comment/blob/ed05a2e5134c846ceace093250fdedf697a6fe75/README.md?plain=1#L267

**Comment by MishaKav** [comment]
you can still use the HTML response in this line
https://github.com/MishaKav/pytest-coverage-comment/blob/ed05a2e5134c846ceace093250fdedf697a6fe75/.github/workflows/update-coverage-on-readme.yml#L32

Try to remove the "echo" line with "HTML"
https://github.com/MishaKav/pytest-coverage-comment/blob/0e5d9396932b388ef7f313db17977815050b0cd5/README.md?plain=1#L153

**Comment by HagegeR** [comment]
I'll try this, btw the first link you sent also use the wrong id

**Comment by HagegeR** [comment]
outputs.content is not valid, did you mean outputs.coverageHtml? I get an empty result from outputs.content

**Comment by MishaKav** [comment]
Yes, I mean, just remove this line 
```yaml
echo "Coverage Html - ${{ steps.coverageComment.outputs.coverageHtml }}" 
```

**Comment by HagegeR** [comment]
I tried many things, in the end the only thing that worked was using ${{ steps.coverageComment.outputs.summaryReport }}
it adds "" that I don't need, but the content is here at least

**Comment by MishaKav** [comment]
Thanks for sharing
