### ISSUE TITLE
Use Release using Floating Tag

### ISSUE THREAD

**Issue by chandanpg** [MishaKav/pytest-coverage-comment#182]
Hi,

I have noticed that you are release using semantic version but can you use floating tag as well like other Actions are used. 
ex. 
Currently your latest release is pointing to below commit. So when you will release a new, you v1 tag should point to same point a well. 
v1.1.52 -> fa1c641d7e3fa1d98ed95d5f658ccd638b774628
v1 -> fa1c641d7e3fa1d98ed95d5f658ccd638b774628

So in future when you will release 
v1.1.53 -> <new commit>
v1 -> <new commit>

This way who are using your action, dont have to change every time their side when you are releasing something from your side.

**Comment by MishaKav** [comment]
Will do this on the next release,
Meanwhile, you may use `MishaKav/pytest-coverage-comment@main`, always pointing to `latest` and widely used by other devs.

**Comment by MishaKav** [comment]
`v1` tag is [released](https://github.com/MishaKav/pytest-coverage-comment/releases/tag/v1)

Thank you
