### ISSUE TITLE
I want information on Tests, Skipped, Failures, Errors, Time in outputs

### ISSUE THREAD

**Issue by satodaiki** [MishaKav/pytest-coverage-comment#24]
hi.

As the title suggests, I want information such as Tests, Skipped, Failures, Errors, Time that can be obtained from junitxml.

Is it possible to respond?

**Comment by MishaKav** [comment]
Done.
You can see the documentation of the outputs in [Readme](https://github.com/marketplace/actions/pytest-coverage-comment#output-variables)

**Comment by satodaiki** [comment]
@MishaKav 
Thank you for your prompt response!
