### ISSUE TITLE
I want to know about failed/error/skipped tests

### ISSUE THREAD

**Issue by satodaiki** [MishaKav/pytest-coverage-comment#26]
hello.

Currently, I don't know what the failed / error / skipped test is in the content output in the PR comment.
Is it possible to output this in the comment as well?
Also, can this be included in the outputs?

Please consider it.

**Comment by satodaiki** [comment]
add implemention.
Verification please!

#27

**Comment by MishaKav** [comment]
I format a little your code, update `Readme`, and made a release version to `1.1.10`.
You can use it now like: 

```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.10
```

**Big thanks** for contributing to the plugin! 🎉

P.S. I'm also adding you as a contributor to [Readme](https://github.com/MishaKav/pytest-coverage-comment#our-contibutors)
