### ISSUE TITLE
Missing Software License

### ISSUE THREAD

**Issue by laserprec** [MishaKav/pytest-coverage-comment#28]
Hi there! Great work in presenting the coverage reports in such a concise but pretty manner 😃! I would love to use your tool in my own project, but it looks like you guys have not clarified what software license you will be releasing this GitHub Action under...

**Comment by MishaKav** [comment]
The type of license (MIT) was specified in [package.json](https://github.com/MishaKav/pytest-coverage-comment/blob/main/package.json), now I add it explicitly to the repo [LICENSE](https://github.com/MishaKav/pytest-coverage-comment/blob/main/LICENSE)
