### ISSUE TITLE
Option to only show changed files in comment report

### ISSUE THREAD

**Issue by wallies** [MishaKav/pytest-coverage-comment#43]
Example here https://github.com/wallies/cobertura-action/blob/master/src/action.js

**Comment by MishaKav** [comment]
Can you please add some screenshots or more explanation from what you want, I can't understand.
Do you want to see changed files compared to when or what?

**Comment by wallies** [comment]
So when I make a PR currently the github action makes a comment with the pytest report, but it currently shows the whole report. Where as it would be nice if there was an option to parse to the github action to only show changes files in the report, e.g. I only changed one file in the PR, so it only shows that file in the report

**Comment by MishaKav** [comment]
Your request was implemented, you can just run `MishaKav/pytest-coverage-comment@main` or use `MishaKav/pytest-coverage-comment@v1.1.17`
Thank you.

**Comment by wallies** [comment]
Wow thanks so much @MishaKav
