### ISSUE TITLE
"Missing" lines in "Cover" column

### ISSUE THREAD

**Issue by aaronkurz** [MishaKav/pytest-coverage-comment#49]
The coverage report column "Cover" shows the information from the "Missing" column.

In my project:
<img width="835" alt="Screenshot 2022-03-08 at 15 53 02" src="https://user-images.githubusercontent.com/62746723/157262762-e365ce67-1d13-4e2c-bfa6-95e20bbc6969.png">

In your own PR in this repo #48 
<img width="831" alt="Screenshot 2022-03-08 at 15 53 23" src="https://user-images.githubusercontent.com/62746723/157262829-a68c04d5-da65-47a8-b5f7-0b25dbb9736b.png">

**Comment by MishaKav** [comment]
I broke it by mistake on the previous PR, now I fixed it.
You can just run `MishaKav/pytest-coverage-comment@main` or use `MishaKav/pytest-coverage-comment@v1.1.20`
Thank you.

**Comment by aaronkurz** [comment]
Thank you! I can confirm that it works as expected again! 🥳
