### ISSUE TITLE
color is not being properly forwarded to badge

### ISSUE THREAD

**Issue by KennethEnevoldsen** [MishaKav/pytest-coverage-comment#6]
Seems like color is not being properly forwarded to the batch. It also seems like the echo statement shows that it is not properly extracted: 

![Screenshot 2021-06-01 at 16 15 23](https://user-images.githubusercontent.com/23721977/120338574-a6223300-c2f4-
11eb-8dde-5104a4173e8b.png)

(screenshot taken from actions on this Github)

**Comment by MishaKav** [comment]
Thanks for the reporting. Fixed the issue ([see the workflow](https://github.com/MishaKav/pytest-coverage-comment/runs/2731486549))

![image](https://user-images.githubusercontent.com/289035/120548766-65611180-c3fb-11eb-8b42-a93ee2efc1e8.png)
