### ISSUE TITLE
Display elapsed Time in minutes

### ISSUE THREAD

**Issue by jhonatan-lopes** [MishaKav/pytest-coverage-comment#61]
Hi,

For tests that take a long time, the `Time` variable in seconds is not very useful. Is it possible to display the elapsed time in minutes?

For instance, right now my comment is displayed like this:

Tests | Skipped | Failures | Errors | Time
-- | -- | -- | -- | --
199 | 0 :zzz:  | 0 :x:  | 0 :fire:  | 595.039s :watch:

It would be nice if there was an option when setting up the workflow to have it displayed like this:

Tests | Skipped | Failures | Errors | Time
-- | -- | -- | -- | --
199 | 0 :zzz:  | 0 :x:  | 0 :fire:  | 9.91min :watch:

**Comment by MishaKav** [comment]
Add this feature, you can just run MishaKav/pytest-coverage-comment@main or use MishaKav/pytest-coverage-comment@v1.1.26

![image](https://user-images.githubusercontent.com/289035/164779764-5959b7fc-73f5-4d97-83e3-dd03cbafc711.png)

Thank you

**Comment by jhonatan-lopes** [comment]
That's awesome, thank you very much!
