### ISSUE TITLE
Error: Generating coverage report. Cannot destructure property 'name' of 'item' as it is null.

### ISSUE THREAD

**Issue by colin99d** [MishaKav/pytest-coverage-comment#64]
I am trying to add this coverage checker to our large repository. There seems to be an issue creating the proper coverage report.
<img width="879" alt="Screen Shot 2022-04-26 at 7 20 03 AM" src="https://user-images.githubusercontent.com/72827203/165288913-206b85f9-b3cb-47b6-ae88-865bbc861c58.png">

I modified our Github Actions workflow to show everything being exported. The link to the issue is here: https://github.com/OpenBB-finance/OpenBBTerminal/runs/6174383671?check_suite_focus=true
<img width="527" alt="Screen Shot 2022-04-26 at 7 20 40 AM" src="https://user-images.githubusercontent.com/72827203/165289009-896f4c81-e086-4f61-9226-d252f0eeb362.png">
 The above 4 sections show the tests ran, then the two desired output files, then show this coverage reporter which is currently failing.

**Comment by MishaKav** [comment]
Thank you for the great example. I fixed a bug.
You can just run `MishaKav/pytest-coverage-comment@main` or use MishaKav/pytest-coverage-comment@v1.1.27`
Please update me if it works now, I didn't test my plugin on such big repos.
Thank you.

**Comment by colin99d** [comment]
<img width="1025" alt="Screen Shot 2022-04-26 at 3 06 36 PM" src="https://user-images.githubusercontent.com/72827203/165373983-20447511-b4bd-4413-8ca1-27b48af7ffb5.png">
Thanks for the quick response! The report now runs error-free; however, it does not show the individual breakdown for files. Is this something that can be fixed or is our repository just too large?

**Comment by MishaKav** [comment]
can you please provide me the content of `pytest-coverage.txt`?

**Comment by MishaKav** [comment]
I see the problem, you set this setting: `report-only-changed-files: true`
so in such case, it will show in the table only the changed files, in your commit, I saw that you changed only the readme file, so it didn't has any files to put in the table.

**Comment by colin99d** [comment]
I see!! Thanks for the help MishaKav! This repo is super useful.

**Comment by MishaKav** [comment]
GlaThank you, glad to hear that, it was the purpose of the action )
I have the [same action](https://github.com/MishaKav/jest-coverage-comment) for `jest` (tests for `node/javascript`)

**Comment by MishaKav** [comment]
@colin99d after your confusion, I release a feature that will give an indication for this.
- When you enable `report-only-changed-files`, you will see a small "dot" near the title, that indicates that it shows only reported files.
- In case you will update only `README.md` files, when you open a collapse, it will show you.

![image](https://user-images.githubusercontent.com/289035/165396000-2da8a74d-63e0-4266-bf26-329d9c81e58d.png)


You can just run MishaKav/pytest-coverage-comment@main or use `MishaKav/pytest-coverage-comment@v1.1.28`

**Comment by colin99d** [comment]
Awesome! I got one more issue for you that relates.
<img width="377" alt="Screen Shot 2022-04-26 at 5 37 27 PM" src="https://user-images.githubusercontent.com/72827203/165396679-89823c47-b85d-4c4d-b6f0-5dc2c8df9523.png">
On the PR I have been talking about we changed two files with less than 100% code coverage to test (fa_controller.py and loggers.py). However, these are not showing up in the coverage report. It was working fine on a smaller repo, so I believe this a is a large repo glitch again.
<img width="1094" alt="Screen Shot 2022-04-26 at 5 38 49 PM" src="https://user-images.githubusercontent.com/72827203/165396849-04ceec59-fb80-4dac-9026-0c582e750466.png">

**Comment by MishaKav** [comment]
As I see on your commit [f80c0b4](https://github.com/OpenBB-finance/OpenBBTerminal/pull/1740/commits/f80c0b41ab9821b1e22993c4804c1a20c8bf2f42) you changed only `test.yml` file.
It takes the changes from the `commit` and not full PR (maybe I can get all `changed` files from PR, need to check it)

You always can check it on the action itself.
<img width="756" alt="image" src="https://user-images.githubusercontent.com/289035/165398464-bcd6f380-3d2f-4a8a-869e-c4d7c8331d80.png">

**Comment by MishaKav** [comment]
@colin99d I checked this again when your action runs on `push` it will contain only changed files that belong to this **commit**.
When you will run on the `pull_request` event, it will report tall files that changed on the **full PR**.

**Comment by colin99d** [comment]
I see. I tried just removing `report-only-changed-files: true` and now it only shows the failure in coverage for one file and not all of them.
