### ISSUE TITLE
Multiple Comments

### ISSUE THREAD

**Issue by colin99d** [MishaKav/pytest-coverage-comment#66]
When using the coverage commenter a new comment is added each time. This happens regardless of whether `create-new-comment` is set implicitly or explicitly. Feel free to checkout out this pr to see what I mean: https://github.com/OpenBB-finance/OpenBBTerminal/pull/1740

**Comment by MishaKav** [comment]
it create multiple comments when it runs on `push` event (each comment belongs to each commit).
If you will run it on `pull_request` only, then it will update the last comment.

**Comment by colin99d** [comment]
Great to know! Thanks for the insight.
