### ISSUE TITLE
Move from node 12 to node 16

### ISSUE THREAD

**Issue by andypols** [MishaKav/pytest-coverage-comment#88]
Using this action is now causing deprecation warnings.

https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/

**Comment by MishaKav** [comment]
@andypols Thanks for letting me know.
I fixed it and release new version that fix this `warning`, you can use:

```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@main
```
or use a specific version
```yaml
- name: Pytest Coverage Comment
  uses: MishaKav/pytest-coverage-comment@v1.1.36
```

**Comment by andypols** [comment]
@MishaKav Awesome - thanks
