### ISSUE TITLE
Error when clicking the links in the comment report

### ISSUE THREAD

**Issue by duarteocarmo** [MishaKav/pytest-coverage-comment#92]
When I click one of these links: 

![image](https://user-images.githubusercontent.com/26342344/202169027-d1a1a1d9-36bf-40bb-a743-fd38f0466734.png)

I'm brought to a 404.. 

![image](https://user-images.githubusercontent.com/26342344/202169092-63bf690f-c8d8-4b2b-8d87-12ecaaf1fc69.png)

**Comment by MishaKav** [comment]
Can you please show the url it generate ?

**Comment by duarteocarmo** [comment]
Sure, example: 
https://github.com/my-org-name/my-repo-name/blob/d7cf5be64a53616bc63cb20519a7dae122b6cf93/folder/file.py#L209-L210

**Comment by MishaKav** [comment]
looks good, I can't understand where the problem is.
Can you provide the correct URL? You can take the URL from some commit, maybe then I can understood.

**Comment by duarteocarmo** [comment]
It's from a private repository, but here is an example: 
https://github.com/amplemarket/ml-email-data-extraction/blob/12a389cb998a0e38efe9e7bac468f24a3b54406d/api/main.py#L1-L4

**Comment by duarteocarmo** [comment]
I have access to the repo, but the link seems broken: 

![image](https://user-images.githubusercontent.com/26342344/203575107-86d44540-6c0f-426c-8fd2-783349708ea4.png)

**Comment by MishaKav** [comment]
it looks normal, lets's try to check if all parameters are matching, please check all 5 parameters and reply for each of them:
- is your user name `amplemarket`?
- is your repo name `ml-email-data-extraction`?
- do you have commit number `12a389cb998a0e38efe9e7bac468f24a3b54406d` ?
- do you have a folder called `api` in the root of the repo?
- do you have the file called `main.py` in the `api` directory?

Maybe when you try to access the file, you are not in your login?

**Comment by duarteocarmo** [comment]
> is your user name amplemarket?

NO! duarteocarmo - amplemarket is the org name. 

> is your repo name ml-email-data-extraction?

Correct. 

> do you have commit number 12a389cb998a0e38efe9e7bac468f24a3b54406d ?

Correct. 

> do you have a folder called api in the root of the repo?

No. The `api` folder is at `src/api`

> do you have the file called main.py in the api directory?

Yes. At `src/api/main.py`

**Comment by MishaKav** [comment]
got you.
it's a common use case, try to add the property `coverage-path-prefix`

```yaml
- name: Pytest coverage comment
  uses: MishaKav/pytest-coverage-comment@main
  with:
    pytest-coverage-path: ./pytest-coverage.txt
    coverage-path-prefix: api/
```

**Comment by duarteocarmo** [comment]
Ah gotcha. Do you mean `coverage-path-prefix: src/`?

**Comment by MishaKav** [comment]
yes, I mean `overage-path-prefix: src/` )

**Comment by duarteocarmo** [comment]
Gotcha :) thanks a lot!!
